### ISSUE TITLE
Dataset Link is not reachable

### ISSUE THREAD

**Issue by taritkandpal-bo** [HuantWang/FUNDED_NISL#10]
The link to the dataset (http://nisl.cn1.utools.club/tifs/) or the link to the website (http://www.leogoat.site/) is not reachable.

**Comment by HuantWang** [comment]
The website cannot be visited in the future, which is not belong to me, so I don't have access.
But I am going to build a new website in the future. ( Maybe 3 months later )

Please send me an E-mail and I will give you a dataset application form.
