### ISSUE TITLE
module 'FUNDED.data.data.data_preprocess' has no attribute 'Preprocess_test'

### ISSUE THREAD

**Issue by Although1998** [HuantWang/FUNDED_NISL#12]
When I tried to run test.py, I met a problem, the traceback is listed below
![G`_W$ 4Q07GI{_MV5KS8CM2](https://user-images.githubusercontent.com/41273629/201511244-8ce05865-57bd-4716-9061-ec79a2cdad19.png)
Is data_preprocess.py incomplete? If so, can I have the complete code?

**Comment by hyunvis** [comment]
I have same problem 
Did you solved?

**Comment by HuantWang** [comment]
Hi, sorry for the late reply. The test.py wasn't used during our tutorial, so we may not have tested it. 
But we will fix this file and extend our tutorial before next week.

**Comment by jie-2000** [comment]
hi,we have modified the code. You can refer to the following commands:
`$ cd NISL_TIFS2021/FUNDED/cli`
`$ CUDA_VISIBLE_DEVICES=2 python test.py GGNN GraphBinaryClassification ../data/data/data/cve/badall --storedModel_path "./trained_model/GGNN_GraphBinaryClassification__2023-02-01_05-36-00_f1 = 0.800_best.pkl"`
