### ISSUE TITLE
Where is the code for Java Data Preprocessing

### ISSUE THREAD

**Issue by XinyeYang** [HuantWang/FUNDED_NISL#14]
With the same idea like parsing c/c++ above,we construct all relationships in different edges using [soot] and [jdt].

$ cd NISL_TIFS2021/EdgesGenerationAndDataPreprocess/Java_jdt_AST_CDFG/src/main/java/yoshikihigo/tinypdg/
$ java Main.java sourceFilePath savafilePath

I can't find the related file in the project.

**Comment by 1350562074** [comment]
Hello, have you fixed that?  What's the "EdgesGenerationAndDataPreprocess"?
