### ISSUE TITLE
joern cpg.runScript("graph/all.sc")这个命令运行显示all.sc:5: not found: value gremlin

### ISSUE THREAD

**Issue by zhipeng-web** [HuantWang/FUNDED_NISL#19]
使用joern获得源代码的控制流和数据流时，cpg.runScript("graph/all.sc")这个命令运行显示all.sc:5: not found: value gremlin，这是什么原因呢，gremlinpython这个包已经安装了，版本是3.4.6

**Comment by HuantWang** [comment]
Hi, sorry for the late reply. Can you please double check the version of Joern is 0.3?  I guess it's nothing to do with gremlin package.

@xxrz Can you please take a look at this problem and update the Joern version on README.md?

**Comment by zhipeng-web** [comment]
Hello Author, I am using joern version 1.1.172. The question I asked was a little strange, it worked fine when I ran it on my friend's computer, but it got an error when I ran it on mine, but we both had the same environment, so I found it particularly strange.











独钓寒江雪

---原始邮件---
发件人: "Huanting ***@***.***&gt;
发送时间: 2023年7月27日(周四) 凌晨0:24
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [HuantWang/FUNDED_NISL] joern cpg.runScript("graph/all.sc")这个命令运行显示all.sc:5: not found: value gremlin (Issue #19)




 
Hi, sorry for the late reply. Can you please double check the version of Joern is 0.3?  I guess it's nothing to do with gremlin package.
 
@xxrz Can you please take a look at this problem and update the Joern version on README.md?

**Comment by HuantWang** [comment]
We can provide a Docker container to help establish the environment later. 
Thanks for your feedback. If you have any other questions, feel free to ask me here or via email (because I don't always check the GitHub messages, apologise).

**Comment by zhipeng-web** [comment]
&nbsp; &nbsp;I'm sorry for replying to you so late. Because I was ill in hospital some time ago, I replied to you so late. If possible, could you please send me the docker? Thank you very much.

独钓寒江雪
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "HuantWang/FUNDED_NISL"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年10月10日(星期二) 晚上7:00
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [HuantWang/FUNDED_NISL] joern cpg.runScript("graph/all.sc")这个命令运行显示all.sc:5: not found: value gremlin (Issue #19)





 
We can provide a Docker container to help establish the environment later.
 Thanks for your feedback. If you have any other questions, feel free to ask me here or via email (because I don't always check the GitHub messages, apologise).
