### ISSUE TITLE
Java files processing

### ISSUE THREAD

**Issue by 1350562074** [HuantWang/FUNDED_NISL#20]
Could you please provide the data processing code for Java files? What's the " EdgesGenerationAndDataPreprocess"?

**Comment by HuantWang** [comment]
Hi, I'm sorry for the delayed reply; I haven't been noticing messages recently.

I have the Java data processing code ready. Please check  [here ](https://github.com/HuantWang/FUNDED_NISL#java) if this is what you need.

Additionally, the module called "EdgesGenerationAndDataPreprocess" handles the data processing.

**Comment by 1350562074** [comment]
I'm sorry I can't find the dir "EdgesGenerationAndDataPreprocess" in your project.  Could you provide it ?

**Comment by HuantWang** [comment]
Apologies for the delayed response. "EdgesGenerationAndDataPreprocess" is just a placeholder name we use during testing. You can access the Main.java file by following [this link](https://github.com/HuantWang/FUNDED_NISL/blob/5f9ed4dc86eb7c2c532bde37960b2019183affa5/Edge_processing/slicec_7edges_funcblock/src/main/java/sevenEdges/Main.java). I hope it proves helpful.
