### ISSUE TITLE
Can't find java and php related processing programs

### ISSUE THREAD

**Issue by zzulb** [HuantWang/FUNDED_NISL#24]
I can't find any java and php related processing programs. Do c/c++, java, and php use the same Main.java file?

$ cd NISL_TIFS2021/EdgesGenerationAndDataPreprocess/Java_jdt_AST_CDFG/src/main/java/yoshikihigo/tinypdg/
$ java Main.java sourceFilePath savafilePath

$ cd NISL_TIFS2021/EdgesGenerationAndDataPreprocess/php_swift/src/php/main
$ java TestPhp.java sourceFilePath savafilePath

$ cd NISL_TIFS2021/EdgesGenerationAndDataPreprocess/php_swift/src/swift3/main
$ java TestSwift3.java sourceFilePath savafilePath

**Comment by HuantWang** [comment]
Sorry for the late reply. Please check [here](https://github.com/HuantWang/FUNDED_NISL/tree/5f9ed4dc86eb7c2c532bde37960b2019183affa5/Edge_processing/slicec_7edges_funcblock/src/main/java) for Java preprocessing.

For PHP and Swift preprocessing code, we haven't published it here. It will be published with another paper next year. I will keep you updated. Sorry about that. 

You can also preprocess follow our paper with [Anltr](https://www.antlr.org/). Please let me know if you have any other questions.
