### ISSUE TITLE
Adjusting batch size

### ISSUE THREAD

**Issue by WJ-8** [HuantWang/FUNDED_NISL#25]
I meet the problem 
```
tensorflow.python.framework.errors_impl.InternalError:  Blas GEMM launch failed : a.shape=(1451673, 100), b.shape=(100, 16), m=1451673, n=16, k=100
         [[node dense_1/MatMul (defined at /home/wj/anaconda3/envs/funded/lib/python3.7/site-packages/tensorflow_core/python/framework/ops.py:1751) ]] [Op:__forward__internal_call_7111]
```

I have checked TensorFlow and Cuda, and I believe it is due to insufficient graphics memory

**Comment by HuantWang** [comment]
Hi, is everything going well? Sorry for the late reply. 
It seems that this issue is related to TensorFlow. Could you please check the TensorFlow version to confirm it matches the suggested one we have tested in requirements.txt?

**Comment by WJ-8** [comment]
This problem comes from WSL, which will automatically terminate my program. Simply set up a daemon to solve the problem
