### ISSUE TITLE
对比实验部分的实验数据可以公开么？

### ISSUE THREAD

**Issue by BrainLyh** [HuantWang/FUNDED_NISL#26]
论文方案和其他方案的对比结果详细数据可以公开么？

**Comment by HuantWang** [comment]
Hi, sorry for the late reply. Of course, we are happy to provide any useful information if it's available.
Could you please talk more about your interested information?

**Comment by HuantWang** [comment]
Hi, I will colse this issue. If you still have any questions, please feel free to send me an email or reopen the issue. Thank you.
