### ISSUE TITLE
May I ask if the file you provided does not include CWE-77/test cases, that is, there is no. c file？Thanks a lot

### ISSUE THREAD

**Issue by 664730** [HuantWang/FUNDED_NISL#29]

**Comment by HuantWang** [comment]
Hi,

The .c file associated with CWE-77 is included in our zip file. 
After unzipping the dataset file, you can find the C files in the following location: TIFS_Data\SARD\before\CWE-77\0source.

Feel free to let me know if you have any questions.

Cheers,
Huanting
