### ISSUE TITLE
Data Preprocessing for Java is not available 

### ISSUE THREAD

**Issue by nashid** [HuantWang/FUNDED_NISL#3]
Artifact to generate the edges for Java is missing. 

It is mentioned in the paper, the authors are using **Soot**. In the readme, it is mentioned edges are constructed using **Soot and JDT**.

Unfortunately, we do not find the artifacts for generating edges are available in the repository.

Are you planning to share them?

**Comment by HuantWang** [comment]
Hi, due to our cooperation with the Industry, the code and data of JAVA are out of our current public plan.
However, we are willing to discuss any relevant technical details with you. :-)
