### ISSUE TITLE
dataset

### ISSUE THREAD

**Issue by dkf123** [HuantWang/FUNDED_NISL#31]
Hello, how do you get the content of data/data/our_map_all.txt?

**Comment by HuantWang** [comment]
Hi,

This text file contains the structural keywords for vector mapping.

It was created by first collecting AST keywords using Joern's static analysis, followed by training a Word2Vec model, which was then saved to this text file to enable vector loading.

While this approach was effective at the time, as it was developed five years ago, more advanced techniques are now available that offer improved results for vector mapping.

**Comment by dkf123** [comment]
你好，
我尝试将模型gnn.py中的消息传递层mp_layer和全局交换层GraphGlobalExchange注释后，训练结果和测试结果依然可以达到您给的效果，可以详细说明一下吗？期待您的回复。

谢谢！


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "HuantWang/FUNDED_NISL"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年10月30日(星期三) 晚上8:25
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [HuantWang/FUNDED_NISL] dataset (Issue #31)





 
Hi,
 
This text file contains the structural keywords for vector mapping.
 
It was created by first collecting AST keywords using Joern's static analysis, followed by training a Word2Vec model, which was then saved to this text file to enable vector loading.
 
While this approach was effective at the time, as it was developed five years ago, more advanced techniques are now available that offer improved results for vector mapping.
