### ISSUE TITLE
dataset request

### ISSUE THREAD

**Issue by QiuJYWX** [HuantWang/FUNDED_NISL#4]
Hi Huant,

Thanks for your time and attention. We have sent u the dataset application email but didn't receive any reply. Is there any updates?

Kind regards,
Junyang

**Comment by HuantWang** [comment]
Sorry, I have checked my inbox today and found no unanswered emails with data application forms attached in there. 
Could u please send an email one more time to me and attach the dataset application form (you could download it from our website).
