### ISSUE TITLE
May I get your email？The previous email has expired.And I want ask some questions

### ISSUE THREAD

**Issue by CaoBinghao** [HuantWang/FUNDED_NISL#6]

**Comment by HuantWang** [comment]
Sure,  please contact me [here ](wanghuanting@stumail.nwu.edu.cn)

**Comment by CaoBinghao** [comment]
not found

**Comment by CaoBinghao** [comment]
![image](https://user-images.githubusercontent.com/91325962/134856073-daea5e20-1a7f-4e1d-a358-8cf5f235c6dd.png)

**Comment by HuantWang** [comment]
Please try [this one](schwa@leeds.ac.uk)
