### ISSUE TITLE
when i use Main.java(C&C++),it rised an error

### ISSUE THREAD

**Issue by WJ-8** [HuantWang/FUNDED_NISL#7]
![image](https://user-images.githubusercontent.com/47672646/136648848-cb2ec5d2-339b-4766-a72a-32371a25f7fa.png)
how could i solve it?

**Comment by HuantWang** [comment]
@GaryHf @xxrz Please take a look here, thanks.

**Comment by xxrz** [comment]
This is a problem with environment configuration. For simplicity, you can use an IDE such as IDEA to run instead of the CMD.

**Comment by TwjLoveCode** [comment]
@xxrz 你好，还在吗。用IDEA提示org.eclipse.cdt.core.dom.ast不存在。查阅cd的github发现cdt是依附于eclipse使用的，请问您当时是用的eclipse还是IDEA等其他
