### ISSUE TITLE
cpg.runScript  error

### ISSUE THREAD

**Issue by weizhigp** [HuantWang/FUNDED_NISL#8]
I have modified the generated result path in graph/all.sc
![3IPB~4E7V RT@ _M)}4`BNU](https://user-images.githubusercontent.com/49153427/139534412-fb538639-4a62-4ce1-b5ac-88065bfc6d64.png)
I could not ﬁnd a similar problem online,How could I solve it?

**Comment by weizhigp** [comment]
eeeeeeem,the problem is solved when I use the absolute path

**Comment by ReUsea** [comment]
我也在尝试复现这篇论文，可以交流一下吗
