### ISSUE TITLE
数据集问题

### ISSUE THREAD

**Issue by ReUsea** [HuantWang/FUNDED_NISL#9]
您好，这个网站 http://nisl.cn1.utools.club/tifs/依然不可访问，请问可以获取您的数据集吗

**Comment by NikolasBielski** [comment]
http://nisl.cn1.utools.club/tifs/
本站依然不可访问.

**Comment by Tommasil** [comment]
您好，请问http://nisl.cn1.utools.club/tifs/   有替代网址了吗？谢谢您的无私付出

**Comment by HuantWang** [comment]
The website cannot be visited in the future, which is not belong to me, so I don't have access. 
But I am going to build a new website in the future. ( Maybe 3 months later )

**Comment by HuantWang** [comment]
Dataset can be applied via Email. Please send me an Email and I will give you a dataset application form.
